**NumPy (Numerical Python)**


*   Efficient storage and manipulation of numerical arrays is absolutely fundamental to the process of doing data science.
*   Numy is a specialized tool for handling such numerical arrays.


*   NumPy arrays are like Python's built-in list type, but NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size.

*   NumPy arrays form the core of nearly the entire ecosystem of data science tools in
Python.
*   Thus, learning NumPy to use it effectively will be valuable no matter what aspect of
data science interests you.










**Import Numpy**

In [1]:
import numpy

But, by convention, most of the people in Python data science world will import numpy as
np as an alias.

In [2]:
import numpy as np

**Numpy Version**

In [3]:
np.__version__

'1.22.4'

**Creating Arrays from Python Lists**

In [4]:
#integer array:
np.array([2,4,6,8])

array([2, 4, 6, 8])

Remember that, NumPy arrays contain the same type of data. If does not match, it will
upcast if possible.

In [5]:
# Upcast to floating point array:
np.array([2.5, 4, 6.7, 8, 10])

array([ 2.5,  4. ,  6.7,  8. , 10. ])

In [6]:
# Explicitly set the datatype using `dtype` keyword.
np.array([2, 4, 6, 8, 10], dtype = 'float32')

array([ 2.,  4.,  6.,  8., 10.], dtype=float32)

**Creating Arrays from Scratch**

Especially for larger arrays, it is more efficient to create arrays from scratch using
routines built into NumPy.

In [7]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [8]:
# Create a length-10 floating point array filled with zeros
np.zeros(10, dtype=np.int64) # float64 is default size for float of this

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# Create a 3x4 floating-point array filled with ones
np.ones((3,4), dtype=np.int64) # int64 is default size for int of this system (

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [10]:
# Create a 3x4 array filled with 2.1416
np.full((3,4), 2.1416)

array([[2.1416, 2.1416, 2.1416, 2.1416],
       [2.1416, 2.1416, 2.1416, 2.1416],
       [2.1416, 2.1416, 2.1416, 2.1416]])

In [11]:
# Create an array filled with a linear sequence
# using np.arange(start, end, step)
# (this is similar to the built-in range() function)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3,3))

array([[0.63255104, 0.62277276, 0.18355426],
       [0.66376746, 0.57394692, 0.68349954],
       [0.39455294, 0.21142675, 0.54954224]])

In [14]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[-0.89639063,  0.43814182, -0.07360051],
       [ 1.48534721, -0.43294645, -0.60597359],
       [-0.00509252,  1.27709399, -0.94894232]])

In [15]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0,10,(3,3))

array([[0, 1, 3],
       [6, 4, 6],
       [5, 2, 2]])

In [16]:
# Create a 5x5 identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
# Create an uninitialized array of five integers
# The values will be whatever happens to already exist at that memory location
np.empty(5)

array([1., 1., 1., 1., 1.])

**NumPy Array Attributes**

In [31]:
# seed for reproducibility
# Ensure that the same random arrays are generated each time this code is run
np.random.seed(0)

x1= np.random.randint(10, size=6) #one dimentional array
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [26]:
x1 # One-dimensional array

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [25]:
x2 # Two-dimensional array

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [32]:
x3 # Three-dimensional array

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [36]:
# Example of NumPy array attributes
print("x3 ndim: ", x3.ndim) #ndim (the number of dimensions)
print("x3 shape: ", x2.shape) #shape (the size of each dimension)
print("x3 size: ", x3.size) #

x3 ndim:  3
x3 shape:  (3, 4)
